### ISSUE TITLE
Categorizing words

### ISSUE THREAD

**Issue by afifit** [TechnionYearlyProject/IntelligentCompanies#25]
As part of the NLP module we need the ability to categorize words/concepts, for the purpose of generating queries.

Ron and I couldn't figure how to do it in Watson. We can't simply give it a word and get back it's category, because the is a minimum length requirement and a valid English sentence.

Some workarounds I thought about are:

1. Generating a grammatically correct English sentence with no meaning. Something like "The <word>  is <word> because <word> is <word> and <word>". This is the simplest and fastest solution but it makes mistakes (not that rarely).
2. Definition from a dictionary. This works slightly better but companies and products might not have a definition.
3. A Wikipedia passage - providing the Wikipedia article. Works pretty good, but getting to the right wikipedia page might be difficult (Did you know [Java](https://en.wikipedia.org/wiki/Java) is an island?). Also there [are many APIs](https://www.mediawiki.org/wiki/API:Client_code#Java) for wikipedia so it shouldn't be that hard.

I think wikipedia is the best option for categorizing, but it might be too slow because there are a lot of words, so the process might be slow. If there is not wikipedia page then generating a sentence might be  enough, or simply ignoring that word/phrase.

**Comment by TalShinkar** [comment]
Words API seem to solve this issue for now
